yarnPath: .yarn/releases/yarn-sources.js
packageExtensions:
  serverless@*:
    dependencies:
      serverless-offline: "*"
      serverless-webpack: "*"
  serverless-webpack@*:
    dependencies:
      webpack: "*"
  fork-ts-checker-webpack-plugin@*:
    dependencies:
      typescript: "*"
